name: Homebrew Cask Update
on:
  release: { types: released }
  workflow_dispatch:

jobs:
  kyokan-bob:
    runs-on: macos-latest
    steps:
    - name: Update cask nlydv/brew/kyokan-bob
      uses: macauley/action-homebrew-bump-cask@v1.0.0
      with:
        # Required, custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.ACCESS_TOKEN}}
        # Optional, will create tap repo fork in organization
        # org: ORG
        # Bump all outdated casks in this tap
        tap: nlydv/brew
        # Bump only these casks if outdated
        cask: kyokan-bob
        # Optional, if don't want to check for already open PRs
        force: false # true
        # Need to set this input if want to use `brew livecheck`
        livecheck: true
